### Numpy

In [2]:
import numpy as np
# alias

In [3]:
scores = [3,4,5,6,7]

In [4]:
numbers = np.array([3,4,5,6,7])

In [5]:
type(scores)

list

In [7]:
type(numbers)

numpy.ndarray

In [8]:
scores_ = []
for num in scores:
    scores_.append(num * 10)
print(scores_)

[30, 40, 50, 60, 70]


In [9]:
numbers = numbers * 10
print(numbers)

[30 40 50 60 70]


In [13]:
age = np.array([12, 67, 'gh']) # Numpy arrays can be of a single data type

In [12]:
age

array(['12', '67', 'gh'], dtype='<U11')

In [17]:
weights = np.array([45,23,12], dtype = int)

In [18]:
weights

array([45, 23, 12])

In [19]:
# methods are functions residing in a class
amount = np.array([3,4,5,6])

In [20]:
weights

array([45, 23, 12])

In [21]:
type(weights)

numpy.ndarray

In [22]:
weights.ndim

1

In [23]:
age.ndim

1

### Multidim arrays

In [24]:
x = np.array([[2,3,4,5], [2,4,6,8]])

In [25]:
x

array([[2, 3, 4, 5],
       [2, 4, 6, 8]])

In [26]:
x.ndim

2

In [27]:
x.shape

(2, 4)

In [37]:
y = np.array([[6,4,5,6], [4,5,6,7], [4,5,6,7]])

In [35]:
y.ndim

2

In [30]:
y

array([[6, 4, 5, 6],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [38]:
y.shape

(3, 4)

In [39]:
v = np.array([
    [3,4,5],
    [2,3,4],
    [0,7,8],
    [4,7,8]
])

In [40]:
v

array([[3, 4, 5],
       [2, 3, 4],
       [0, 7, 8],
       [4, 7, 8]])

In [41]:
v.ndim

2

In [42]:
v.shape

(4, 3)

In [43]:
c = np.array([[[6,4,5,6], [4,5,6,7], [4,5,6,7]], [[6,4,5,6], [4,5,6,7], [4,5,6,7]]])

In [44]:
c

array([[[6, 4, 5, 6],
        [4, 5, 6, 7],
        [4, 5, 6, 7]],

       [[6, 4, 5, 6],
        [4, 5, 6, 7],
        [4, 5, 6, 7]]])

In [45]:
c.shape

(2, 3, 4)

In [47]:
scores = np.array([3,4,5,6])

In [48]:
len(scores)

4

In [49]:
scores.size

4

In [50]:
score = np.array(['3', '5', '6', '7'])

#### dtype conversion

In [51]:
type(score)

numpy.ndarray

In [53]:
score.dtype 

dtype('<U1')

In [62]:
score = score.astype('int64') # convert

In [63]:
score

array([3, 5, 6, 7], dtype=int64)

In [64]:
score.dtype

dtype('int64')

In [59]:
score = score.astype('float') #variable re-assignment

In [60]:
score

array([3., 5., 6., 7.])

In [61]:
score.dtype

dtype('float64')

### Indexing and Slicing

In [65]:
score

array([3, 5, 6, 7], dtype=int64)

In [66]:
score[0]

3

In [67]:
score[3]

7

In [68]:
score[-1]

7

In [69]:
score[1:3]

array([5, 6], dtype=int64)

In [70]:
x

array([[2, 3, 4, 5],
       [2, 4, 6, 8]])

In [71]:
x[0,0]

2

In [74]:
x[0,3]

5

In [75]:
x[1,3]

8

In [78]:
x[:,2]

array([4, 6])

In [79]:
x[:,1:3]

array([[3, 4],
       [4, 6]])

#### Boolean indexing

In [76]:
x[x>2] # array flattening 

array([3, 4, 5, 4, 6, 8])

In [77]:
x[x <= 5]

array([2, 3, 4, 5, 2, 4])

In [85]:
x_subset = x[x>2]

In [86]:
x

array([[2, 3, 4, 5],
       [2, 4, 6, 8]])

In [81]:
x_subset

array([3, 4, 5, 4, 6, 8])

In [82]:
x.shape

(2, 4)

In [87]:
x_subset = x_subset.reshape(3,2)

In [88]:
x_subset

array([[3, 4],
       [5, 4],
       [6, 8]])

In [89]:
x_new = x_subset.ravel()

In [90]:
x_new

array([3, 4, 5, 4, 6, 8])

### Vectorized operations

In [91]:
x

array([[2, 3, 4, 5],
       [2, 4, 6, 8]])

In [92]:
x = x * 5 # scalar multiplication

In [93]:
x

array([[10, 15, 20, 25],
       [10, 20, 30, 40]])

In [94]:
test_scores = np.array([10,21,19,23])

exam_scores = np.array([24,56,45,68])

In [95]:
# vector/array addition 

total_scores = test_scores + exam_scores

In [96]:
total_scores

array([34, 77, 64, 91])

In [97]:
total_scores = np.add(test_scores, exam_scores)

In [98]:
total_scores

array([34, 77, 64, 91])

### Stats on numpy array

- Descriptive 
 - Measure of CT : mean, median, mode
 - Measure of Variance : S.D, Variance, range, quartile


In [99]:
total_scores

array([34, 77, 64, 91])

In [100]:
total_scores.mean()

66.5

In [101]:
np.mean(total_scores)

66.5

In [102]:
np.median(total_scores)

70.5

In [104]:
np.std(total_scores)

21.0535032714273

In [105]:
var = (np.std(total_scores))**2

In [106]:
var

443.25

### Pandas

 1. Series 
 
 2. DataFrame

In [107]:
import pandas as pd

# from pandas import Series, DataFrame

C:\Users\aaginam\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [108]:
names = pd.Series(['Jane', 'Jacob', 'Chibuzor', 'Cynthia', 'Mo', 'Zita']) 

In [109]:
type(names)

pandas.core.series.Series

In [110]:
names

0        Jane
1       Jacob
2    Chibuzor
3     Cynthia
4          Mo
5        Zita
dtype: object

In [111]:
score = pd.Series([56,34,12,45,78], index=['a', 'b', 'c', 'd', 'e'])

In [112]:
score

a    56
b    34
c    12
d    45
e    78
dtype: int64

In [113]:
score['d']

45

In [114]:
score['e']

78

In [115]:
score['a':'c']

a    56
b    34
c    12
dtype: int64

In [117]:
names[0:4]

0        Jane
1       Jacob
2    Chibuzor
3     Cynthia
dtype: object

In [118]:
score

a    56
b    34
c    12
d    45
e    78
dtype: int64

In [119]:
names = pd.Series(['Tolu', 'Bowa', 'John', 'Peter', 'Sola'], index=['a', 'b', 'c', 'd', 'e'])

In [120]:
names

a     Tolu
b     Bowa
c     John
d    Peter
e     Sola
dtype: object

In [121]:
df = pd.DataFrame({'Names' : names, 'Score' : score})

In [122]:
df

Names  Score
a   Tolu     56
b   Bowa     34
c   John     12
d  Peter     45
e   Sola     78

In [123]:
## create a dataframe that has two columns - Day of the week and Favorite Food.

day_of_week = pd.Series(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])

fav_food = pd.Series(['Bread', 'Plantain', 'Beans', 'Rice', 'Swallow', 'Salad', 'Chicken'])

In [124]:
df2 = pd.DataFrame({'Day of Week' : day_of_week, 'Favorite Food' : fav_food})

In [125]:
df2

Day of Week Favorite Food
0      Monday         Bread
1     Tuesday      Plantain
2   Wednesday         Beans
3    Thursday          Rice
4      Friday       Swallow
5    Saturday         Salad
6      Sunday       Chicken

### Working with real world data

In [129]:
import pandas as pd

In [130]:
data = pd.read_csv('Data_Sheet_Udemy_Courses_-_Music_Courses - Data_Sheet_Udemy_Courses_-_Music_Courses.csv')

In [133]:
data

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

In [132]:
type(data)

pandas.core.frame.DataFrame

In [134]:
data = pd.read_excel('Data_Sheet_Udemy_Courses_-_Music_Courses.xlsx')

In [135]:
data

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

### Data Exploration

In [138]:
data.head()

course_id                                       course_title  \
0      19421              Free Beginner Electric Guitar Lessons   
1     238934  Pianoforall - Incredible New Way To Learn Pian...   
2      41884                Getting Started with Playing Guitar   
3      42271      Complete Guitar System - Beginner to Advanced   
4      26956                            Learn Guitar in 21 Days   

                                                 url  price  num_subscribers  \
0  https://www.udemy.com/beginner-electric-guitar...      0           101154   
1  https://www.udemy.com/pianoforall-incredible-n...    200            75499   
2  https://www.udemy.com/getting-started-with-pla...      0            47652   
3  https://www.udemy.com/complete-guitar-system-b...    145            32935   
4     https://www.udemy.com/learn-guitar-in-21-days/     20            26504   

   num_reviews  num_lectures           level  Rating  content_duration  \
0         1042            95      All Levels    0.88               4.5   
1         7676           362  Beginner Level    0.96              30.0   
2         1141            26      All Levels    0.68               4.0   
3         2713           310      All Levels    0.65              34.0   
4          192            82      All Levels    0.41               2.5   

    published_timestamp              subject  
0  2012-06-15T17:00:33Z  Musical Instruments  
1  2014-08-07T06:27:51Z  Musical Instruments  
2  2013-05-29T15:28:07Z  Musical Instruments  
3  2013-05-29T15:24:47Z  Musical Instruments  
4  2012-10-21T20:36:50Z  Musical Instruments

In [139]:
data.tail()

course_id                                       course_title  \
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments

In [140]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 680 entries, 0 to 679
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_id            680 non-null    int64  
 1   course_title         680 non-null    object 
 2   url                  680 non-null    object 
 3   price                680 non-null    int64  
 4   num_subscribers      680 non-null    int64  
 5   num_reviews          680 non-null    int64  
 6   num_lectures         680 non-null    int64  
 7   level                680 non-null    object 
 8   Rating               680 non-null    float64
 9   content_duration     680 non-null    float64
 10  published_timestamp  680 non-null    object 
 11  subject              680 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 63.9+ KB


In [141]:
data.shape

(680, 12)

In [142]:
data.columns

Index(['course_id', 'course_title', 'url', 'price', 'num_subscribers',
       'num_reviews', 'num_lectures', 'level', 'Rating', 'content_duration',
       'published_timestamp', 'subject'],
      dtype='object')

### Filtering, Slicing and Indexing data

In [147]:
data

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

In [148]:
data['url']

0      https://www.udemy.com/beginner-electric-guitar...
1      https://www.udemy.com/pianoforall-incredible-n...
2      https://www.udemy.com/getting-started-with-pla...
3      https://www.udemy.com/complete-guitar-system-b...
4         https://www.udemy.com/learn-guitar-in-21-days/
                             ...                        
675    https://www.udemy.com/learn-to-play-sweet-chil...
676    https://www.udemy.com/coaching-bundle-rhythm-i...
677    https://www.udemy.com/learn-pirates-of-the-car...
678    https://www.udemy.com/learn-to-play-piano-like...
679         https://www.udemy.com/4-week-rhythm-mastery/
Name: url, Length: 680, dtype: object

In [149]:
data[['url']]

url
0    https://www.udemy.com/beginner-electric-guitar...
1    https://www.udemy.com/pianoforall-incredible-n...
2    https://www.udemy.com/getting-started-with-pla...
3    https://www.udemy.com/complete-guitar-system-b...
4       https://www.udemy.com/learn-guitar-in-21-days/
..                                                 ...
675  https://www.udemy.com/learn-to-play-sweet-chil...
676  https://www.udemy.com/coaching-bundle-rhythm-i...
677  https://www.udemy.com/learn-pirates-of-the-car...
678  https://www.udemy.com/learn-to-play-piano-like...
679       https://www.udemy.com/4-week-rhythm-mastery/

[680 rows x 1 columns]

In [150]:
data[['course_title']]

course_title
0                Free Beginner Electric Guitar Lessons
1    Pianoforall - Incredible New Way To Learn Pian...
2                  Getting Started with Playing Guitar
3        Complete Guitar System - Beginner to Advanced
4                              Learn Guitar in 21 Days
..                                                 ...
675                  Learn to Play Sweet Child of Mine
676  Coaching Course: Rhythm Instruction for Music ...
677  Learn Pirates of the Caribbean by Ear on the P...
678  Learn to Play Piano Like a Pro - Easy Piano Co...
679                              4 Week Rhythm Mastery

[680 rows x 1 columns]

In [174]:
# loc - Label Selection

data.loc[0:10, ['course_title']]

course_title
0               Free Beginner Electric Guitar Lessons
1   Pianoforall - Incredible New Way To Learn Pian...
2                 Getting Started with Playing Guitar
3       Complete Guitar System - Beginner to Advanced
4                             Learn Guitar in 21 Days
5                 The Professional Guitar Masterclass
6               Introduction to Piano - By PGN Piano!
7           Best Beginner Guitar Lessons by Sam Lyons
8                              Acoustic Guitar Basics
9                         Guitar Super System Level 1
10  The Complete Piano & Music Theory Beginners Co...

In [159]:
data.loc[0:50, ['url']].tail()

url
46  https://www.udemy.com/modern-rock-guitar-techn...
47  https://www.udemy.com/fun-ukulele-strumming-co...
48  https://www.udemy.com/magic-of-eb-key-12-piano...
49  https://www.udemy.com/easy-piano-today-play-fe...
50  https://www.udemy.com/3-fingerstyle-guitar-tec...

In [176]:
data[['course_title', 'num_lectures']]

course_title  num_lectures
0                Free Beginner Electric Guitar Lessons            95
1    Pianoforall - Incredible New Way To Learn Pian...           362
2                  Getting Started with Playing Guitar            26
3        Complete Guitar System - Beginner to Advanced           310
4                              Learn Guitar in 21 Days            82
..                                                 ...           ...
675                  Learn to Play Sweet Child of Mine            23
676  Coaching Course: Rhythm Instruction for Music ...             7
677  Learn Pirates of the Caribbean by Ear on the P...             6
678  Learn to Play Piano Like a Pro - Easy Piano Co...            13
679                              4 Week Rhythm Mastery            28

[680 rows x 2 columns]

In [214]:
data.loc[:5, ['course_title', 'num_lectures']]

course_title  num_lectures
0              Free Beginner Electric Guitar Lessons            95
1  Pianoforall - Incredible New Way To Learn Pian...           362
2                Getting Started with Playing Guitar            26
3      Complete Guitar System - Beginner to Advanced           310
4                            Learn Guitar in 21 Days            82
5                The Professional Guitar Masterclass           136

In [170]:
data.loc[2,'course_title']

'Getting Started with Playing Guitar'

In [177]:
data.loc[:10, 'course_id' : 'num_reviews']

course_id                                       course_title  \
0       19421              Free Beginner Electric Guitar Lessons   
1      238934  Pianoforall - Incredible New Way To Learn Pian...   
2       41884                Getting Started with Playing Guitar   
3       42271      Complete Guitar System - Beginner to Advanced   
4       26956                            Learn Guitar in 21 Days   
5      456284                The Professional Guitar Masterclass   
6      583752              Introduction to Piano - By PGN Piano!   
7       59922          Best Beginner Guitar Lessons by Sam Lyons   
8      198690                             Acoustic Guitar Basics   
9      484670                        Guitar Super System Level 1   
10     953152  The Complete Piano & Music Theory Beginners Co...   

                                                  url  price  num_subscribers  \
0   https://www.udemy.com/beginner-electric-guitar...      0           101154   
1   https://www.udemy.com/pianoforall-incredible-n...    200            75499   
2   https://www.udemy.com/getting-started-with-pla...      0            47652   
3   https://www.udemy.com/complete-guitar-system-b...    145            32935   
4      https://www.udemy.com/learn-guitar-in-21-days/     20            26504   
5   https://www.udemy.com/the-professional-guitar-...    200            21701   
6          https://www.udemy.com/introductiontopiano/      0            14922   
7   https://www.udemy.com/best-beginner-guitar-les...     20            14560   
8       https://www.udemy.com/acoustic-guitar-basics/      0            14495   
9   https://www.udemy.com/guitar-super-system-leve...     50            10869   
10  https://www.udemy.com/piano-lessons-music-theo...     50            10435   

    num_reviews  
0          1042  
1          7676  
2          1141  
3          2713  
4           192  
5          1340  
6           772  
7            20  
8           224  
9          2257  
10          665

In [179]:
data.iloc[:10 , [0]]

course_id
0      19421
1     238934
2      41884
3      42271
4      26956
5     456284
6     583752
7      59922
8     198690
9     484670

In [184]:
data.iloc[:5, 0:3]

course_id                                       course_title  \
0      19421              Free Beginner Electric Guitar Lessons   
1     238934  Pianoforall - Incredible New Way To Learn Pian...   
2      41884                Getting Started with Playing Guitar   
3      42271      Complete Guitar System - Beginner to Advanced   
4      26956                            Learn Guitar in 21 Days   

                                                 url  
0  https://www.udemy.com/beginner-electric-guitar...  
1  https://www.udemy.com/pianoforall-incredible-n...  
2  https://www.udemy.com/getting-started-with-pla...  
3  https://www.udemy.com/complete-guitar-system-b...  
4     https://www.udemy.com/learn-guitar-in-21-days/

In [195]:
# conditional selection

data.subject == 'Musical Instruments'

len(data.loc[data.subject == 'Musical Instrument'])

0

In [216]:
data.loc[(data.price > 100) | (data.level == 'Beginner Level'),['course_id', 'price', 'url']].head()

course_id  price                                                url
1      238934    200  https://www.udemy.com/pianoforall-incredible-n...
3       42271    145  https://www.udemy.com/complete-guitar-system-b...
5      456284    200  https://www.udemy.com/the-professional-guitar-...
8      198690      0      https://www.udemy.com/acoustic-guitar-basics/
13     200598    200  https://www.udemy.com/benhewlettharmonicatuiti...

In [203]:
data.loc[data.course_title.notnull()]

course_id                                       course_title  \
0        19421              Free Beginner Electric Guitar Lessons   
1       238934  Pianoforall - Incredible New Way To Learn Pian...   
2        41884                Getting Started with Playing Guitar   
3        42271      Complete Guitar System - Beginner to Advanced   
4        26956                            Learn Guitar in 21 Days   
..         ...                                                ...   
675    1216340                  Learn to Play Sweet Child of Mine   
676    1026762  Coaching Course: Rhythm Instruction for Music ...   
677    1223240  Learn Pirates of the Caribbean by Ear on the P...   
678    1224186  Learn to Play Piano Like a Pro - Easy Piano Co...   
679    1234656                              4 Week Rhythm Mastery   

                                                   url  price  \
0    https://www.udemy.com/beginner-electric-guitar...      0   
1    https://www.udemy.com/pianoforall-incredible-n...    200   
2    https://www.udemy.com/getting-started-with-pla...      0   
3    https://www.udemy.com/complete-guitar-system-b...    145   
4       https://www.udemy.com/learn-guitar-in-21-days/     20   
..                                                 ...    ...   
675  https://www.udemy.com/learn-to-play-sweet-chil...     20   
676  https://www.udemy.com/coaching-bundle-rhythm-i...    125   
677  https://www.udemy.com/learn-pirates-of-the-car...     20   
678  https://www.udemy.com/learn-to-play-piano-like...     35   
679       https://www.udemy.com/4-week-rhythm-mastery/     20   

     num_subscribers  num_reviews  num_lectures           level  Rating  \
0             101154         1042            95      All Levels    0.88   
1              75499         7676           362  Beginner Level    0.96   
2              47652         1141            26      All Levels    0.68   
3              32935         2713           310      All Levels    0.65   
4              26504          192            82      All Levels    0.41   
..               ...          ...           ...             ...     ...   
675                0            0            23      All Levels    0.31   
676                0            0             7  Beginner Level    0.06   
677                0            0             6      All Levels    0.08   
678                0            0            13  Beginner Level    0.78   
679                0            0            28      All Levels    0.01   

     content_duration   published_timestamp              subject  
0            4.500000  2012-06-15T17:00:33Z  Musical Instruments  
1           30.000000  2014-08-07T06:27:51Z  Musical Instruments  
2            4.000000  2013-05-29T15:28:07Z  Musical Instruments  
3           34.000000  2013-05-29T15:24:47Z  Musical Instruments  
4            2.500000  2012-10-21T20:36:50Z  Musical Instruments  
..                ...                   ...                  ...  
675          1.500000  2017-06-30T17:33:29Z  Musical Instruments  
676          0.633333  2017-03-10T17:06:46Z  Musical Instruments  
677          0.533333  2017-05-22T17:14:43Z  Musical Instruments  
678          0.516667  2017-05-30T00:19:02Z  Musical Instruments  
679          2.500000  2017-07-05T16:07:44Z  Musical Instruments  

[680 rows x 12 columns]

### Data Cleaning

In [143]:
data.isnull()

course_id  course_title    url  price  num_subscribers  num_reviews  \
0        False         False  False  False            False        False   
1        False         False  False  False            False        False   
2        False         False  False  False            False        False   
3        False         False  False  False            False        False   
4        False         False  False  False            False        False   
..         ...           ...    ...    ...              ...          ...   
675      False         False  False  False            False        False   
676      False         False  False  False            False        False   
677      False         False  False  False            False        False   
678      False         False  False  False            False        False   
679      False         False  False  False            False        False   

     num_lectures  level  Rating  content_duration  published_timestamp  \
0           False  False   False             False                False   
1           False  False   False             False                False   
2           False  False   False             False                False   
3           False  False   False             False                False   
4           False  False   False             False                False   
..            ...    ...     ...               ...                  ...   
675         False  False   False             False                False   
676         False  False   False             False                False   
677         False  False   False             False                False   
678         False  False   False             False                False   
679         False  False   False             False                False   

     subject  
0      False  
1      False  
2      False  
3      False  
4      False  
..       ...  
675    False  
676    False  
677    False  
678    False  
679    False  

[680 rows x 12 columns]

In [144]:
data.isnull().sum()

course_id              0
course_title           0
url                    0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
Rating                 0
content_duration       0
published_timestamp    0
subject                0
dtype: int64

In [219]:
(data.isnull().sum() / len(data)) * 100

course_title           0.0
url                    0.0
price                  0.0
num_subscribers        0.0
num_reviews            0.0
num_lectures           0.0
level                  0.0
Rating                 0.0
content_duration       0.0
published_timestamp    0.0
subject                0.0
dtype: float64

In [145]:
data.isna().sum()

course_id              0
course_title           0
url                    0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
Rating                 0
content_duration       0
published_timestamp    0
subject                0
dtype: int64

In [146]:
data.duplicated().sum()

0

In [237]:
data = data.drop_duplicates(subset=['course_id'])

#### Dealing with null values

1. Replacement - 
2. Drop

In [221]:
data_copy = data.copy()

data.drop(['num_reviews', 'url'], axis=1, inplace=True)

In [222]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 680 entries, 0 to 679
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_title         680 non-null    object 
 1   price                680 non-null    int64  
 2   num_subscribers      680 non-null    int64  
 3   num_lectures         680 non-null    int64  
 4   level                680 non-null    object 
 5   Rating               680 non-null    float64
 6   content_duration     680 non-null    float64
 7   published_timestamp  680 non-null    object 
 8   subject              680 non-null    object 
dtypes: float64(2), int64(3), object(4)
memory usage: 47.9+ KB


In [223]:
data.describe()

price  num_subscribers  num_lectures      Rating  content_duration
count  680.000000       680.000000    680.000000  680.000000        680.000000
mean    49.558824      1245.130882     38.316176    0.308912          2.854387
std     41.187592      5676.381419     42.739700    0.303799          3.470463
min      0.000000         0.000000      4.000000    0.000000          0.483333
25%     20.000000        31.000000     14.000000    0.070000          1.000000
50%     40.000000       138.000000     25.000000    0.150000          2.000000
75%     50.000000       870.250000     43.000000    0.520000          3.500000
max    200.000000    101154.000000    362.000000    1.000000         38.000000

In [226]:
# SSOT

data.price.fillna(data.price.mean(), inplace=True)

In [ ]:

data.price.fillna(method='bfill', inplace=True)

In [227]:
data.head()

course_title  price  num_subscribers  \
0              Free Beginner Electric Guitar Lessons      0           101154   
1  Pianoforall - Incredible New Way To Learn Pian...    200            75499   
2                Getting Started with Playing Guitar      0            47652   
3      Complete Guitar System - Beginner to Advanced    145            32935   
4                            Learn Guitar in 21 Days     20            26504   

   num_lectures           level  Rating  content_duration  \
0            95      All Levels    0.88               4.5   
1           362  Beginner Level    0.96              30.0   
2            26      All Levels    0.68               4.0   
3           310      All Levels    0.65              34.0   
4            82      All Levels    0.41               2.5   

    published_timestamp              subject  
0  2012-06-15T17:00:33Z  Musical Instruments  
1  2014-08-07T06:27:51Z  Musical Instruments  
2  2013-05-29T15:28:07Z  Musical Instruments  
3  2013-05-29T15:24:47Z  Musical Instruments  
4  2012-10-21T20:36:50Z  Musical Instruments

In [228]:
data['level'].value_counts()

level
All Levels            324
Beginner Level        266
Intermediate Level     78
Expert Level           12
Name: count, dtype: int64

In [231]:
# data['level'].replace({'Expert Level' : 'Advanced Level'}, inplace=True)

data['level'] = data['level'].replace({'Expert Level' : 'Advanced Level'})

In [232]:
data['level'].value_counts()

level
All Levels            324
Beginner Level        266
Intermediate Level     78
Advanced Level         12
Name: count, dtype: int64

In [233]:
## removing rows that are null

data.dropna(axis=0, inplace=True)

In [ ]:
data.dropna(axis=1, inplace=True, how='all')

In [238]:
data.head()

course_title  price  num_subscribers  \
0              Free Beginner Electric Guitar Lessons      0           101154   
1  Pianoforall - Incredible New Way To Learn Pian...    200            75499   
2                Getting Started with Playing Guitar      0            47652   
3      Complete Guitar System - Beginner to Advanced    145            32935   
4                            Learn Guitar in 21 Days     20            26504   

   num_lectures           level  Rating  content_duration  \
0            95      All Levels    0.88               4.5   
1           362  Beginner Level    0.96              30.0   
2            26      All Levels    0.68               4.0   
3           310      All Levels    0.65              34.0   
4            82      All Levels    0.41               2.5   

    published_timestamp              subject  
0  2012-06-15T17:00:33Z  Musical Instruments  
1  2014-08-07T06:27:51Z  Musical Instruments  
2  2013-05-29T15:28:07Z  Musical Instruments  
3  2013-05-29T15:24:47Z  Musical Instruments  
4  2012-10-21T20:36:50Z  Musical Instruments

In [239]:
data.price = data.price.astype('str')

C:\Users\aaginam\AppData\Local\Temp\ipykernel_11868\3446387995.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.price = data.price.astype('str')


In [240]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 676 entries, 0 to 679
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_title         676 non-null    object 
 1   price                676 non-null    object 
 2   num_subscribers      676 non-null    int64  
 3   num_lectures         676 non-null    int64  
 4   level                676 non-null    object 
 5   Rating               676 non-null    float64
 6   content_duration     676 non-null    float64
 7   published_timestamp  676 non-null    object 
 8   subject              676 non-null    object 
dtypes: float64(2), int64(2), object(5)
memory usage: 52.8+ KB


In [244]:
data['price'] = "N" + " " + data['price']


C:\Users\aaginam\AppData\Local\Temp\ipykernel_11868\1959980761.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['price'] = "N" + " " + data['price']


In [245]:
data.head()

course_title        price  \
0              Free Beginner Electric Guitar Lessons    N N N N 0   
1  Pianoforall - Incredible New Way To Learn Pian...  N N N N 200   
2                Getting Started with Playing Guitar    N N N N 0   
3      Complete Guitar System - Beginner to Advanced  N N N N 145   
4                            Learn Guitar in 21 Days   N N N N 20   

   num_subscribers  num_lectures           level  Rating  content_duration  \
0           101154            95      All Levels    0.88               4.5   
1            75499           362  Beginner Level    0.96              30.0   
2            47652            26      All Levels    0.68               4.0   
3            32935           310      All Levels    0.65              34.0   
4            26504            82      All Levels    0.41               2.5   

    published_timestamp              subject  
0  2012-06-15T17:00:33Z  Musical Instruments  
1  2014-08-07T06:27:51Z  Musical Instruments  
2  2013-05-29T15:28:07Z  Musical Instruments  
3  2013-05-29T15:24:47Z  Musical Instruments  
4  2012-10-21T20:36:50Z  Musical Instruments

In [247]:
data_copy.head()

course_title  \
0              Free Beginner Electric Guitar Lessons   
1  Pianoforall - Incredible New Way To Learn Pian...   
2                Getting Started with Playing Guitar   
3      Complete Guitar System - Beginner to Advanced   
4                            Learn Guitar in 21 Days   

                                                 url  price  num_subscribers  \
0  https://www.udemy.com/beginner-electric-guitar...      0           101154   
1  https://www.udemy.com/pianoforall-incredible-n...    200            75499   
2  https://www.udemy.com/getting-started-with-pla...      0            47652   
3  https://www.udemy.com/complete-guitar-system-b...    145            32935   
4     https://www.udemy.com/learn-guitar-in-21-days/     20            26504   

   num_reviews  num_lectures           level  Rating  content_duration  \
0         1042            95      All Levels    0.88               4.5   
1         7676           362  Beginner Level    0.96              30.0   
2         1141            26      All Levels    0.68               4.0   
3         2713           310      All Levels    0.65              34.0   
4          192            82      All Levels    0.41               2.5   

    published_timestamp              subject  
0  2012-06-15T17:00:33Z  Musical Instruments  
1  2014-08-07T06:27:51Z  Musical Instruments  
2  2013-05-29T15:28:07Z  Musical Instruments  
3  2013-05-29T15:24:47Z  Musical Instruments  
4  2012-10-21T20:36:50Z  Musical Instruments

In [251]:
data['price'] = data['price'].str.replace("N N N N","")

In [252]:
data.head()

course_title price  num_subscribers  \
0              Free Beginner Electric Guitar Lessons     0           101154   
1  Pianoforall - Incredible New Way To Learn Pian...   200            75499   
2                Getting Started with Playing Guitar     0            47652   
3      Complete Guitar System - Beginner to Advanced   145            32935   
4                            Learn Guitar in 21 Days    20            26504   

   num_lectures           level  Rating  content_duration  \
0            95      All Levels    0.88               4.5   
1           362  Beginner Level    0.96              30.0   
2            26      All Levels    0.68               4.0   
3           310      All Levels    0.65              34.0   
4            82      All Levels    0.41               2.5   

    published_timestamp              subject  
0  2012-06-15T17:00:33Z  Musical Instruments  
1  2014-08-07T06:27:51Z  Musical Instruments  
2  2013-05-29T15:28:07Z  Musical Instruments  
3  2013-05-29T15:24:47Z  Musical Instruments  
4  2012-10-21T20:36:50Z  Musical Instruments

In [253]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 676 entries, 0 to 679
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_title         676 non-null    object 
 1   price                676 non-null    object 
 2   num_subscribers      676 non-null    int64  
 3   num_lectures         676 non-null    int64  
 4   level                676 non-null    object 
 5   Rating               676 non-null    float64
 6   content_duration     676 non-null    float64
 7   published_timestamp  676 non-null    object 
 8   subject              676 non-null    object 
dtypes: float64(2), int64(2), object(5)
memory usage: 52.8+ KB


In [254]:
data['price'] = data['price'].astype('int64')

In [255]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 676 entries, 0 to 679
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_title         676 non-null    object 
 1   price                676 non-null    int64  
 2   num_subscribers      676 non-null    int64  
 3   num_lectures         676 non-null    int64  
 4   level                676 non-null    object 
 5   Rating               676 non-null    float64
 6   content_duration     676 non-null    float64
 7   published_timestamp  676 non-null    object 
 8   subject              676 non-null    object 
dtypes: float64(2), int64(3), object(4)
memory usage: 52.8+ KB


In [256]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 676 entries, 0 to 679
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   course_title         676 non-null    object 
 1   price                676 non-null    int64  
 2   num_subscribers      676 non-null    int64  
 3   num_lectures         676 non-null    int64  
 4   level                676 non-null    object 
 5   Rating               676 non-null    float64
 6   content_duration     676 non-null    float64
 7   published_timestamp  676 non-null    object 
 8   subject              676 non-null    object 
dtypes: float64(2), int64(3), object(4)
memory usage: 52.8+ KB


In [257]:
data.to_csv('Cleaned Data.csv')

In [259]:
data.to_excel('Cleaned Data.xlsx')